name = "lapce-elm"
version = "0.0.1"
author = "VarLad"
display-name = "Elm (elm-language-server)"
description = "Elm support for the Lapce editor (powered by elm-language-server)"
wasm = "lapce-elm.wasm"
